"""Initial schema with unique indexes

Revision ID: 7443ab81ae5b
Revises: 
Create Date: 2026-06-04 20:50:05.048299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7443ab81ae5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gym', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(length=50), nullable=False),
    sa.Column('octagon', sa.JSON(), nullable=True),
    sa.Column('total_sparrings', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('last_sparring', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_gym_ranking', 'users', ['gym', 'ranking'], unique=False)
    op.create_index('idx_sport_weight', 'users', ['sport', 'weight'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_gym'), 'users', ['gym'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gym', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rankings_gym_ranking', 'rankings', ['gym', 'ranking'], unique=False)
    op.create_index('idx_gym_user', 'rankings', ['gym', 'user_id'], unique=False)
    op.create_index(op.f('ix_rankings_gym'), 'rankings', ['gym'], unique=False)
    op.create_table('sparrings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challenger_id', sa.String(length=36), nullable=False),
    sa.Column('opponent_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('challenger_vote', sa.String(length=50), nullable=True),
    sa.Column('opponent_vote', sa.String(length=50), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('gym', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gym_sport', 'sparrings', ['gym', 'sport'], unique=False)
    op.create_index('idx_status_scheduled', 'sparrings', ['status', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_sparrings_challenger_id'), 'sparrings', ['challenger_id'], unique=False)
    op.create_index(op.f('ix_sparrings_gym'), 'sparrings', ['gym'], unique=False)
    op.create_index(op.f('ix_sparrings_opponent_id'), 'sparrings', ['opponent_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sparring_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vote', sa.String(length=50), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sparring_id'], ['sparrings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sparring_user', 'votes', ['sparring_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_votes_sparring_id'), 'votes', ['sparring_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_sparring_id'), table_name='votes')
    op.drop_index('idx_sparring_user', table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_sparrings_opponent_id'), table_name='sparrings')
    op.drop_index(op.f('ix_sparrings_gym'), table_name='sparrings')
    op.drop_index(op.f('ix_sparrings_challenger_id'), table_name='sparrings')
    op.drop_index('idx_status_scheduled', table_name='sparrings')
    op.drop_index('idx_gym_sport', table_name='sparrings')
    op.drop_table('sparrings')
    op.drop_index(op.f('ix_rankings_gym'), table_name='rankings')
    op.drop_index('idx_gym_user', table_name='rankings')
    op.drop_index('idx_gym_ranking', table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_gym'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_sport_weight', table_name='users')
    op.drop_index('idx_gym_ranking', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
